stages:
  - test
  - package
  - packagetest
  - deploy

test:debian:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-setuptools python3-pytest-runner python3-pytest python3-pytest-cov python3-xmltodict python3-requests python3-pycryptodome
    - python3 -m venv .venv
    - ./.venv/bin/pip install .[dev,test]
    - ./.venv/bin/ruff check .
    - ./.venv/bin/ruff format --check .
    - ./.venv/bin/mypy .
    - ./.venv/bin/pytest .

  tags:
    - debian

test:archlinux:
  stage: test
  script:
    - pacman -Sy python python-setuptools python-pytest python-pytest-cov python-xmltodict python-requests python-pycryptodomex --noconfirm
    - python3 -m venv .venv
    - ./.venv/bin/pip install .[dev,test]
    - ./.venv/bin/ruff check .
    - ./.venv/bin/ruff format --check .
    - ./.venv/bin/mypy .
    - ./.venv/bin/pytest .

  tags:
    - archlinux

package:debian:
  stage: package
  script:
    - apt-get update -qy
    - apt-get install -y python3-pytest-runner python3-stdeb python3-pytest python3-pytest-cov python3-xmltodict python3-requests dh-python python3-pycryptodome
    - rm -rf "./deb_dist"
    - python3 setup.py --command-packages=stdeb.command bdist_deb
  tags:
    - debian

  artifacts:
    paths:
      - deb_dist/*.deb
    expire_in: 1d

package:archlinux:
  stage: package
  script:
    - pacman -Sy python-pip sudo openssh binutils fakeroot python-xmltodict python-requests python-pycryptodomex python-setuptools base-devel --noconfirm
    - useradd -m -G users -s /bin/bash package
    - chown -R package:users archlinux
    - cd archlinux
    - sudo -H -u package makepkg -f
  tags:
    - archlinux

  artifacts:
    paths:
      - archlinux/python-huawei-lte-api*
    expire_in: 1d

packagetest:debian:
  stage: packagetest
  script:
    - apt-get update -qy
    - cd deb_dist
    - apt install ./*.deb -qy
  tags:
    - debian
  dependencies:
    - package:debian

packagetest:archlinux:
  stage: packagetest
  script:
    - cd archlinux
    - pacman -Sy
    - pacman -U python-huawei-lte-api*.pkg.tar.zst --noconfirm
  tags:
    - archlinux
  dependencies:
    - package:archlinux

repoupdate:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y
    - apt-get install twine python3-setuptools python3-wheel python3-build -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/any/python-huawei-lte-api*.pkg.tar.zst'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/python3-huawei-lte-api*.deb'
    - scp archlinux/python-huawei-lte-api*.pkg.tar.zst www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/any
    - scp deb_dist/*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - ssh www-data@repository '/var/www/repository.salamek.cz/deb-pub-update.sh'
    - ssh www-data@repository '/var/www/repository.salamek.cz/arch-pub-update.sh'
    - python3 -m build
    - twine upload dist/*
  dependencies:
    - package:archlinux
    - package:debian
  tags:
    - debian
  only:
    - tags
